### PR TITLE
Elixir 1.10.0

### PR DESCRIPTION
**Pull request by renews**
Update to elixir 1.10.0

### CODE REVIEW

**Comment by renews** [comment]
@bitwalker Hello there, please check if you can merge this :)

**Comment by renews** [comment]
Hey, @bitwalker :) Sry to bother again :) Can you check this PR? Thanks!

**Comment by StareIntoTheBeard** [comment]
@bitwalker bump...

**Comment by bitwalker** [comment]
Updates have been merged via another conflicting PR, but thanks for the contribution!

**Pull request closed without merging**
