### PR TITLE
bump to Elixir 1.11

### PR DESCRIPTION
**Pull request by rubysolo**
tty

### CODE REVIEW

**Comment by coladarci** [comment]
@rubysolo wanna bump this to `11.1.1` since this is still open and now there's a newer release? ❤️

**Comment by rubysolo** [comment]
It looks like all Paul's Dockerfiles use explicit version tags for their base images, but I don't see an explicit tag for 1.11.1 yet (only `latest`).

**Comment by rupurt** [comment]
@rubysolo I've opened an issue in the `alpine-elixir` repo https://github.com/bitwalker/alpine-elixir/issues/66

Ideally this would all be automated to avoid things getting out of sync.

**Comment by bitwalker** [comment]
This has been superceded by #68, since I happened to look at that one first. In any case, a 1.11 version has been merged, and should be published soon.

**Pull request closed without merging**
