### PR TITLE
Add curl-dev to fix curl issues

### PR DESCRIPTION
**Pull request by jeroenvisser101**
Curl throws curl: "(48) An unknown option was passed in to libcurl"

see http://stackoverflow.com/a/41651363/2059127

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
This doesn't work yet, some issues with unsatisfiable constraints

**Comment by bitwalker** [comment]
What constraints is it complaining about?

**Comment by jeroenvisser101** [comment]
Hey @bitwalker, it was complaining about a constraint curl placed, which wasn't satisfiable by curl-dev. We did some testings, but it seems that this docker image wasn't updated after the alpine version was increased [here](https://github.com/bitwalker/alpine-erlang/commit/056fc234ee6b8490cd185fdf41f4025be6eb560b), and that causes issues, because curl on Alpine 3.5 works just fine. We'll do additional testing tomorrow

**Comment by bitwalker** [comment]
I can bump the Alpine version to 3.5, that's not an issue.

**Comment by bitwalker** [comment]
I've updated the image, could you give it a look?

**Comment by bitwalker** [comment]
Sorry, that was `alpine-elixir`, updating `alpine-elixir-phoenix` now.

**Comment by jeroenvisser101** [comment]
No worries, let me know when it's updated and I'll pull it in and test 👍

**Comment by bitwalker** [comment]
Just finished!

**Comment by jeroenvisser101** [comment]
Thanks! That fixed the issues regarding curl, closing this now 👍

**Pull request closed without merging**
